// Offline-Helfer: legt die Seiten beim ersten Besuch auf dem Gerät ab.
// Online wird immer zuerst die aktuelle Fassung geholt, ohne Netz die gespeicherte.
// Neue Dateien in DATEIEN eintragen und VERSION hochzählen.
const VERSION = 'v5';
const DATEIEN = [
  '/',
  '/erdmaennchenklasse/guten-morgen/',
  '/manifest.webmanifest',
  '/assets/base.css',
  '/assets/pwa.js',
  '/assets/art/ende.svg',
  '/assets/art/header.svg',
  '/assets/art/karte-wache.svg',
  '/assets/art/klasse-erdmaennchen.svg',
  '/assets/art/klasse-hasen.svg',
  '/assets/fonts/fredoka-latin-500-normal.woff2',
  '/assets/fonts/fredoka-latin-600-normal.woff2',
  '/assets/fonts/fredoka-latin-700-normal.woff2',
  '/assets/fonts/nunito-latin-400-normal.woff2',
  '/assets/fonts/nunito-latin-700-normal.woff2',
  '/assets/fonts/nunito-latin-800-normal.woff2',
  '/assets/icons/icon.svg',
  '/assets/icons/icon-192.png',
  '/assets/icons/icon-512.png',
  '/assets/icons/apple-touch-icon.png',
  '/assets/icons/favicon-32.png',
  '/erdmaennchenklasse/guten-morgen/app/manifest.webmanifest',
  '/erdmaennchenklasse/guten-morgen/app/icon.svg',
  '/erdmaennchenklasse/guten-morgen/app/icon-512.png',
  '/erdmaennchenklasse/guten-morgen/app/icon-192.png',
  '/erdmaennchenklasse/guten-morgen/app/apple-touch-icon.png',
  '/erdmaennchenklasse/guten-morgen/app/favicon-32.png',
  '/hasenklasse/anlaute/',
  '/hasenklasse/anlaute/app/manifest.webmanifest',
  '/hasenklasse/anlaute/app/icon.svg',
  '/hasenklasse/anlaute/app/icon-512.png',
  '/hasenklasse/anlaute/app/icon-192.png',
  '/hasenklasse/anlaute/app/apple-touch-icon.png',
  '/hasenklasse/anlaute/app/favicon-32.png',
  '/assets/art/karte-anlaute.svg',
  '/assets/art/ende-anlaute.svg',
  '/assets/art/anlaute/aehre.svg',
  '/assets/art/anlaute/aepfel.svg',
  '/assets/art/anlaute/affe.svg',
  '/assets/art/anlaute/ameise.svg',
  '/assets/art/anlaute/ampel.svg',
  '/assets/art/anlaute/ananas.svg',
  '/assets/art/anlaute/anker.svg',
  '/assets/art/anlaute/apfel.svg',
  '/assets/art/anlaute/aufzug.svg',
  '/assets/art/anlaute/auge.svg',
  '/assets/art/anlaute/auto.svg',
  '/assets/art/anlaute/baer.svg',
  '/assets/art/anlaute/ball.svg',
  '/assets/art/anlaute/banane.svg',
  '/assets/art/anlaute/baum.svg',
  '/assets/art/anlaute/biene.svg',
  '/assets/art/anlaute/boot.svg',
  '/assets/art/anlaute/dach.svg',
  '/assets/art/anlaute/daumen.svg',
  '/assets/art/anlaute/delfin.svg',
  '/assets/art/anlaute/dino.svg',
  '/assets/art/anlaute/dose.svg',
  '/assets/art/anlaute/drache.svg',
  '/assets/art/anlaute/ei.svg',
  '/assets/art/anlaute/eichhoernchen.svg',
  '/assets/art/anlaute/eimer.svg',
  '/assets/art/anlaute/eis.svg',
  '/assets/art/anlaute/eisbaer.svg',
  '/assets/art/anlaute/elefant.svg',
  '/assets/art/anlaute/ente.svg',
  '/assets/art/anlaute/erdbeere.svg',
  '/assets/art/anlaute/esel.svg',
  '/assets/art/anlaute/eule.svg',
  '/assets/art/anlaute/euro.svg',
  '/assets/art/anlaute/fahrrad.svg',
  '/assets/art/anlaute/feder.svg',
  '/assets/art/anlaute/fisch.svg',
  '/assets/art/anlaute/frosch.svg',
  '/assets/art/anlaute/fuss.svg',
  '/assets/art/anlaute/gabel.svg',
  '/assets/art/anlaute/geschenk.svg',
  '/assets/art/anlaute/giraffe.svg',
  '/assets/art/anlaute/gitarre.svg',
  '/assets/art/anlaute/gurke.svg',
  '/assets/art/anlaute/hand.svg',
  '/assets/art/anlaute/hase.svg',
  '/assets/art/anlaute/haus.svg',
  '/assets/art/anlaute/herz.svg',
  '/assets/art/anlaute/hund.svg',
  '/assets/art/anlaute/hut.svg',
  '/assets/art/anlaute/inliner.svg',
  '/assets/art/anlaute/insekt.svg',
  '/assets/art/anlaute/insel.svg',
  '/assets/art/anlaute/jacke.svg',
  '/assets/art/anlaute/jaguar.svg',
  '/assets/art/anlaute/joghurt.svg',
  '/assets/art/anlaute/jojo.svg',
  '/assets/art/anlaute/kaese.svg',
  '/assets/art/anlaute/kamel.svg',
  '/assets/art/anlaute/katze.svg',
  '/assets/art/anlaute/kerze.svg',
  '/assets/art/anlaute/krone.svg',
  '/assets/art/anlaute/kuh.svg',
  '/assets/art/anlaute/lampe.svg',
  '/assets/art/anlaute/laterne.svg',
  '/assets/art/anlaute/leiter.svg',
  '/assets/art/anlaute/loeffel.svg',
  '/assets/art/anlaute/loewe.svg',
  '/assets/art/anlaute/maus.svg',
  '/assets/art/anlaute/melone.svg',
  '/assets/art/anlaute/moehre.svg',
  '/assets/art/anlaute/mond.svg',
  '/assets/art/anlaute/muetze.svg',
  '/assets/art/anlaute/nase.svg',
  '/assets/art/anlaute/nest.svg',
  '/assets/art/anlaute/nilpferd.svg',
  '/assets/art/anlaute/nudel.svg',
  '/assets/art/anlaute/nuss.svg',
  '/assets/art/anlaute/oel.svg',
  '/assets/art/anlaute/oelkanne.svg',
  '/assets/art/anlaute/ofen.svg',
  '/assets/art/anlaute/ohr.svg',
  '/assets/art/anlaute/oktopus.svg',
  '/assets/art/anlaute/oma.svg',
  '/assets/art/anlaute/opa.svg',
  '/assets/art/anlaute/otter.svg',
  '/assets/art/anlaute/paket.svg',
  '/assets/art/anlaute/pfanne.svg',
  '/assets/art/anlaute/pfeife.svg',
  '/assets/art/anlaute/pferd.svg',
  '/assets/art/anlaute/pfirsich.svg',
  '/assets/art/anlaute/pfote.svg',
  '/assets/art/anlaute/pilz.svg',
  '/assets/art/anlaute/pinguin.svg',
  '/assets/art/anlaute/pinsel.svg',
  '/assets/art/anlaute/pizza.svg',
  '/assets/art/anlaute/puppe.svg',
  '/assets/art/anlaute/quadrat.svg',
  '/assets/art/anlaute/qualle.svg',
  '/assets/art/anlaute/rad.svg',
  '/assets/art/anlaute/rakete.svg',
  '/assets/art/anlaute/raupe.svg',
  '/assets/art/anlaute/regenschirm.svg',
  '/assets/art/anlaute/ring.svg',
  '/assets/art/anlaute/rose.svg',
  '/assets/art/anlaute/saege.svg',
  '/assets/art/anlaute/salat.svg',
  '/assets/art/anlaute/schaf.svg',
  '/assets/art/anlaute/schaukel.svg',
  '/assets/art/anlaute/schlange.svg',
  '/assets/art/anlaute/schnecke.svg',
  '/assets/art/anlaute/schuh.svg',
  '/assets/art/anlaute/seife.svg',
  '/assets/art/anlaute/socke.svg',
  '/assets/art/anlaute/sofa.svg',
  '/assets/art/anlaute/sonne.svg',
  '/assets/art/anlaute/spaten.svg',
  '/assets/art/anlaute/spiegel.svg',
  '/assets/art/anlaute/spinne.svg',
  '/assets/art/anlaute/stern.svg',
  '/assets/art/anlaute/stiefel.svg',
  '/assets/art/anlaute/stift.svg',
  '/assets/art/anlaute/storch.svg',
  '/assets/art/anlaute/stuhl.svg',
  '/assets/art/anlaute/tasse.svg',
  '/assets/art/anlaute/tiger.svg',
  '/assets/art/anlaute/tisch.svg',
  '/assets/art/anlaute/tomate.svg',
  '/assets/art/anlaute/topf.svg',
  '/assets/art/anlaute/turm.svg',
  '/assets/art/anlaute/ueberraschung.svg',
  '/assets/art/anlaute/ufo.svg',
  '/assets/art/anlaute/uhr.svg',
  '/assets/art/anlaute/uhu.svg',
  '/assets/art/anlaute/unterhose.svg',
  '/assets/art/anlaute/waage.svg',
  '/assets/art/anlaute/wal.svg',
  '/assets/art/anlaute/wolke.svg',
  '/assets/art/anlaute/wuerfel.svg',
  '/assets/art/anlaute/wurm.svg',
  '/assets/art/anlaute/zahn.svg',
  '/assets/art/anlaute/zaun.svg',
  '/assets/art/anlaute/zebra.svg',
  '/assets/art/anlaute/zelt.svg',
  '/assets/art/anlaute/zitrone.svg',
  '/assets/art/anlaute/zug.svg',
];

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(VERSION).then((c) => c.addAll(DATEIEN)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((namen) => Promise.all(namen.filter((n) => n !== VERSION).map((n) => caches.delete(n))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== location.origin) return;
  e.respondWith(
    fetch(req)
      .then((antwort) => {
        if (antwort.ok) {
          const kopie = antwort.clone();
          caches.open(VERSION).then((c) => c.put(req, kopie));
        }
        return antwort;
      })
      .catch(() => caches.match(req, { ignoreSearch: true }).then((gespeichert) => gespeichert || Response.error()))
  );
});
